spring:
  application:
    name: irgftpserver
  datasource:
    url: jdbc:postgresql://localhost:5432/ftpserver
    username: ftpserv
    password: De7896543!!##
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ftpserverCP
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    schemas: ftpserver
    table: ftpserver_schema_history
    url: jdbc:postgresql://localhost:5432/ftpserver
    baseline-version: 1
    baseline-description: "Base Migration"
    user: ftpserv
    password: De7896543!!##
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration

#SFTP Server Configuration
sftp:
  server:
    hostkeyalgorithm: RSA
    port: 2221
    keyPath: hostkey.ser
    # Max Packet Size do not change unless you know what you're doing.
    maxWriteDataPacketLength: 32768
    maxLoginAttemptThreshold: 3
    delayBetweenLoginAttempts: 2000
    corePoolSize: 2
    maxPoolSize: 4
    keepAliveTime: 60
    queueCapacity: 50
    initialPasswordChangeRequired: true
    SFTPUsers:
      - username: testuser
        password: password
        directory: /Users/testuser/ftp
        company-id: 1
        company-name: testcompany
        ticket-url: http://localhost:8080/ticket1
        public-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyfKcD9+FVxDMmZcO+/5PzUKo1sxz300x6oPAvRaBtFhYlQk08tecEdHkae9KKwJ6TtjyrqqQwEj2A28Cn8uuiNZ6+Sk3bUng8WYvFw5KH6kRfoSEHH1M8AsapcfOriLFmCkW0bH6F1pRAhu1D9rMK3H4YUQv15j5Oap18hj7XeBZq/y7C2lgMut8B52LSQjcU53DbGqkxKoTNTHnTfVoIbwEtO8trhxJ7BmCHrdnLXgwYfRtLI4gcnGrNM8RlRgJUlqCVpOZqDgw05+YpHuuDL6iw1SE9o/LL1UtEWJkv7KVnBS7XgFd39mQSCL+062nqbeyY7cSR2y5Xf6DuMtNl testuser@localhost"
      - username: testuser2
        password: password
        directory: /Users/testuser2/ftp1
        company-id: 2
        company-name: testcompany2
        ticket-url: http://localhost:8080/ticket2
        public-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyfKcD9+FVxDMmZcO+/5PzUKo1sxz300x6oPAvRaBtFhYlQk08tecEdHkae9KKwJ6TtjyrqqQwEj2A28Cn8uuiNZ6+Sk3bUng8WYvFw5KH6kRfoSEHH1M8AsapcfOriLFmCkW0bH6F1pRAhu1D9rMK3H4YUQv15j5Oap18hj7XeBZq/y7C2lgMut8B52LSQjcU53DbGqkxKoTNTHnTfVoIbwEtO8trhxJ7BmCHrdnLXgwYfRtLI4gcnGrNM8RlRgJUlqCVpOZqDgw05+YpHuuDL6iw1SE9o/LL1UtEWJkv7KVnBS7XgFd39mQSCL+062nqbeyY7cSR2y5Xf6DuMtNl testuser@localhost"

    Users:
      - username: admin
        password: c1c2b928-c0fc-486a-b183-a05a794cff52
        company-name: testcompany





